version: '3.8'

services:
  test-crud-api:
    build: ./
    command: ./postgres.sh db ./test-crud-api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
      - POSTGRES_STORAGE="./test-crud-api/config/config.yaml"
      
  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_STORAGE="./test-crud-api/config/config.yaml"
    ports:
      - 5433:5432