version: "3"
services:
 app:
   build: .
   ports:
     - 8080:8080
   depends_on:
    - db
 db:
   image: postgres
   environment:
         POSTGRES_USER: user
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: news_feed_boot
         PGDATA: /var/lib/postgresql/data
   networks:
      - golang-test-restapi
networks:
  golang-test-restapi:
     driver: bridge    