CREATE TABLE IF NOT EXISTS users 
(
id VARCHAR[11] SERIAL PRIMARY KEY, 
first_name VARCHAR[50] NOT NULL, 
last_name   VARCHAR[50] NOT NULL, 
age  INTEGER NOT NULL,
recordingdate  TIMESTAMP NOT NULL, 
);